name: Build palera1n

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'patches/**'
      - 'include/**'
      - 'Makefile'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (packages)
        run: |
          sudo apt-get -y update
          sudo apt-get -y install mandoc make

      - name: Build Documentation
        run: |
          make -j$(nproc) docs
          mkdir -p ready/docs
          cp docs/*.html docs/mandoc.css docs/palera1n.1 ready/docs

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ready/docs

  build-darwin:
    strategy:
      matrix:
        include:
          - arch: x86_64
            gnu_triple: x86_64-apple-darwin
            os: macosx
            minos: 10.8
          - arch: arm64
            gnu_triple: aarch64-apple-darwin
            os: macosx
            minos: 11.0
          - arch: arm64
            gnu_triple: aarch64-apple-darwin
            os: iphoneos
            minos: 7.0
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo /usr/local/bin/pip3 install jsonschema jinja2
          brew install make autoconf automake pkg-config gnu-sed gettext libtool
          sudo rm -rf /usr/local/Frameworks/Python*

      - name: Setup SDK
        run: echo "SDK=$(xcrun -sdk ${{ matrix.os }} --show-sdk-path)" >> $GITHUB_ENV

      - name: Select correct Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Setup Environment
        run: echo "DESTDIR=$(pwd)/sysroot" >> $GITHUB_ENV

      - name: Build palera1n
        run: |
          mkdir -p ready/builds
          make -j$(sysctl -n hw.ncpu)
          cp src/palera1n ready/builds/palera1n-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: palera1n-${{ matrix.os }}-${{ matrix.arch }}
          path: ready/builds/palera1n-${{ matrix.os }}-${{ matrix.arch }}

  build-linux:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - armel
          - i386
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config autoconf automake

      - name: Build palera1n
        run: |
          mkdir -p ready/builds
          make -j$(nproc)
          cp src/palera1n ready/builds/palera1n-linux-${{ matrix.arch }}

      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: palera1n-linux-${{ matrix.arch }}
          path: ready/builds/palera1n-linux-${{ matrix.arch }}

  finish-build:
    runs-on: ubuntu-latest
    needs: [build-docs, build-darwin, build-linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release Bundle
        run: |
          mkdir -p final_release
          cp -r docs/* final_release/
          cp -r palera1n-*/* final_release/

      - name: Upload Full Release Bundle
        uses: actions/upload-artifact@v4
        with:
          name: palera1n-full-release
          path: final_release
